version: '3.9'

services:
  fetcher:
    build:
      dockerfile: docker/fetcher/Dockerfile
      context: ./
    environment:
      - DB_HOST=postgres
      - UPDATE_PERIOD
      - DB_PASSWORD
      - SHEETS_DOC_ID
      - SHEETS_SERVICE_ACCOUNT_KEY
      - CURRENCY_INFO_URL
    restart: unless-stopped
    depends_on:
      - postgres
    logging:
      driver: json-file
      options:
        max-size: 1G

  api:
    build:
      dockerfile: docker/flask/Dockerfile
      context: ./
    restart: unless-stopped
    depends_on:
      - postgres
    logging:
      driver: json-file
      options:
        max-size: 1G

  api-proxy:
    image: ntdesmond/nginx-api-proxy:latest
    ports:
      - "80:80"
    environment:
      TARGET_HOSTNAME: "api:8000"
    depends_on:
      - api
    restart: unless-stopped
    logging:
      driver: none

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    logging:
      driver: none