version: '3.9'

services:
  app:
    build:
      dockerfile: ./docker/Dockerfile
      context: ./
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - postgres
    logging:
      driver: json-file
      options:
        max-size: 1G

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD
    restart: unless-stopped
    logging:
      driver: none